/**
 * LeafMesh's on-disk blob — P11 step 3, plan §5.
 *
 * Only the authoritative half of the topology is written: `v.co`, `e.v1/v2`,
 * `c.v`, `c.next`, `l.c`, `l.next`, `f.l`, and every non-`TEMP` attribute
 * layer. Disk and radial cycles, `c.e`, `c.prev`, `c.l`, `l.size`, `l.f` and
 * `f.listCount` are regenerated by `rebuildDerivedTopo()` on load, so roughly
 * two thirds of the columns never reach the file.
 *
 * The blob is dense: handles are renumbered into live-iteration order as it is
 * written, so a file never carries a tombstone. That is done through a remap
 * table rather than by calling `compact()` on the mesh being saved — saving
 * must not move an element out from under a caller holding its handle (active
 * element, tool state, an undo step). Nothing in the file depends on the old
 * numbering, so the renumbering is invisible once loaded.
 *
 * This module stays free of `scripts/` imports like the rest of the core; the
 * nstructjs hook that hands the blob to a `.wproj` lives in `leafmesh.ts`.
 *
 * Byte order is the host's, as it is for LiteMesh's engine blob. Every
 * practical target is little-endian, and a file is not a wire format.
 */

import {AttrFlags, AttrType, DOMAIN_COUNT, Domain} from './attrs.js'
import {ELEM_NONE, ElemArray, type TypedArray} from './elem_array.js'
import {LeafMesh} from './topo.js'

/** `LEAF` then `MSH` + NUL, as the two little-endian u32s the header reads. */
const MAGIC_0 = 0x4641454c
const MAGIC_1 = 0x0048534d

export const LEAFMESH_BLOB_VERSION = 1

/** Every typed-array kind an attribute column can hold, by tag. */
const CTORS = [Float32Array, Float64Array, Int32Array, Int16Array, Uint8Array] as const

function ctorTag(data: TypedArray): number {
  const i = CTORS.findIndex((c) => data instanceof c)
  if (i < 0) {
    throw new Error('leafmesh: unserializable column type')
  }
  return i
}

function align4(n: number): number {
  return (n + 3) & ~3
}

/**
 * Append-only byte writer. Everything is kept 4-byte aligned so that bulk
 * column writes can go through a typed-array view instead of a per-element
 * `DataView` loop — the per-byte path is what made LiteMesh's load a startup
 * hotspot, and it is worth not repeating.
 */
class BlobWriter {
  private chunks: Uint8Array[] = []
  private len = 0

  u32(...values: number[]): void {
    const a = new Uint32Array(values)
    this.push(new Uint8Array(a.buffer))
  }

  /** Bulk column data, padded out to the alignment invariant. */
  bytes(view: TypedArray): void {
    this.push(new Uint8Array(view.buffer, view.byteOffset, view.byteLength))
    const pad = align4(view.byteLength) - view.byteLength
    if (pad > 0) {
      this.push(new Uint8Array(pad))
    }
  }

  /** One value at full precision, so a float column's fill survives. */
  f64(value: number): void {
    this.bytes(new Float64Array([value]))
  }

  /** A length-prefixed UTF-8 string. */
  str(s: string): void {
    const bytes = new TextEncoder().encode(s)
    this.u32(bytes.length)
    this.bytes(bytes)
  }

  finish(): Uint8Array {
    const out = new Uint8Array(this.len)
    let at = 0
    for (const c of this.chunks) {
      out.set(c, at)
      at += c.length
    }
    return out
  }

  private push(chunk: Uint8Array): void {
    this.chunks.push(chunk)
    this.len += chunk.length
  }
}

class BlobReader {
  private at = 0

  constructor(private readonly bytes: Uint8Array) {}

  u32(n = 1): Uint32Array {
    // A copy, not a view: the incoming Uint8Array carries no alignment
    // guarantee of its own, so a view onto its buffer may not be constructible.
    const out = new Uint32Array(n)
    new Uint8Array(out.buffer).set(this.bytes.subarray(this.at, this.at + n * 4))
    this.at += n * 4
    return out
  }

  one(): number {
    return this.u32(1)[0]
  }

  /** `n` elements of `ctor`, copied out of the blob. */
  read<T extends TypedArray>(ctor: {new (n: number): T; BYTES_PER_ELEMENT: number}, n: number): T {
    const out = new ctor(n)
    const bytes = n * ctor.BYTES_PER_ELEMENT
    new Uint8Array(out.buffer).set(this.bytes.subarray(this.at, this.at + bytes))
    this.at += align4(bytes)
    return out
  }

  f64(): number {
    return this.read(Float64Array, 1)[0]
  }

  str(): string {
    const n = this.one()
    const s = new TextDecoder().decode(this.bytes.subarray(this.at, this.at + n))
    this.at += align4(n)
    return s
  }
}

/** Live handles in ascending order, plus the old-handle → row table. */
function denseOrder(array: ElemArray): {order: Int32Array; remap: Int32Array} {
  const order = new Int32Array(array.count)
  const remap = new Int32Array(Math.max(array.used, 1)).fill(ELEM_NONE)

  let n = 0
  for (const i of array) {
    remap[i] = n
    order[n++] = i
  }
  return {order, remap}
}

/** `src[order[i]]`, with `ELEM_NONE` preserved through `remap`. */
function gatherHandles(src: Int32Array, order: Int32Array, remap: Int32Array): Int32Array {
  const out = new Int32Array(order.length)
  for (let i = 0; i < order.length; i++) {
    const h = src[order[i]]
    out[i] = h === ELEM_NONE ? ELEM_NONE : remap[h]
  }
  return out
}

function gatherAttr(column: {data: TypedArray; size: number}, order: Int32Array): TypedArray {
  const {data, size} = column
  const out = new (data.constructor as {new (n: number): TypedArray})(order.length * size)
  for (let i = 0; i < order.length; i++) {
    const s = order[i] * size
    const d = i * size
    for (let k = 0; k < size; k++) {
      out[d + k] = data[s + k]
    }
  }
  return out
}

export function serializeLeafMesh(mesh: LeafMesh): Uint8Array {
  const w = new BlobWriter()
  const arrays = mesh.arrays
  const dense = arrays.map(denseOrder)

  const v = dense[Domain.VERT]
  const e = dense[Domain.EDGE]
  const c = dense[Domain.CORNER]
  const l = dense[Domain.LOOP]
  const f = dense[Domain.FACE]

  w.u32(MAGIC_0, MAGIC_1, LEAFMESH_BLOB_VERSION, 0)
  w.u32(v.order.length, e.order.length, c.order.length, l.order.length, f.order.length)

  const co = new Float32Array(v.order.length * 3)
  for (let i = 0; i < v.order.length; i++) {
    const s = v.order[i] * 3
    co[i * 3] = mesh.v.co[s]
    co[i * 3 + 1] = mesh.v.co[s + 1]
    co[i * 3 + 2] = mesh.v.co[s + 2]
  }
  w.bytes(co)

  w.bytes(gatherHandles(mesh.e.v1, e.order, v.remap))
  w.bytes(gatherHandles(mesh.e.v2, e.order, v.remap))
  w.bytes(gatherHandles(mesh.c.v, c.order, v.remap))
  w.bytes(gatherHandles(mesh.c.next, c.order, c.remap))
  w.bytes(gatherHandles(mesh.l.c, l.order, c.remap))
  w.bytes(gatherHandles(mesh.l.next, l.order, l.remap))
  w.bytes(gatherHandles(mesh.f.l, f.order, l.remap))

  const layers = []
  for (let domain = 0; domain < DOMAIN_COUNT; domain++) {
    for (const layer of mesh.attrs.persistentLayers(domain)) {
      layers.push(layer)
    }
  }

  w.u32(layers.length)
  for (const layer of layers) {
    w.u32(layer.domain, layer.type, layer.flags, ctorTag(layer.column.data))
    w.u32(layer.column.size, 0)
    w.f64(layer.column.fill)
    w.str(layer.name)
    w.bytes(gatherAttr(layer.column, dense[layer.domain].order))
  }

  return w.finish()
}

/** Always builds a fresh mesh: the loader owns the numbering, not the caller. */
export function deserializeLeafMesh(bytes: Uint8Array): LeafMesh {
  const mesh = new LeafMesh()
  const r = new BlobReader(bytes)

  const [m0, m1, version] = r.u32(4)
  if (m0 !== MAGIC_0 || m1 !== MAGIC_1) {
    throw new Error('leafmesh: not a LeafMesh blob')
  }
  if (version > LEAFMESH_BLOB_VERSION) {
    throw new Error(`leafmesh: blob version ${version} is newer than ${LEAFMESH_BLOB_VERSION}`)
  }

  const counts = r.u32(DOMAIN_COUNT)
  const arrays = mesh.arrays
  for (let domain = 0; domain < DOMAIN_COUNT; domain++) {
    // Handing out 0..n-1 in order: the file is dense, so the free list is
    // empty and `alloc()` walks the high-water mark.
    arrays[domain].reserve(counts[domain])
    for (let i = 0; i < counts[domain]; i++) {
      arrays[domain].alloc()
    }
  }

  mesh.v.co.set(r.read(Float32Array, counts[Domain.VERT] * 3))
  mesh.e.v1.set(r.read(Int32Array, counts[Domain.EDGE]))
  mesh.e.v2.set(r.read(Int32Array, counts[Domain.EDGE]))
  mesh.c.v.set(r.read(Int32Array, counts[Domain.CORNER]))
  mesh.c.next.set(r.read(Int32Array, counts[Domain.CORNER]))
  mesh.l.c.set(r.read(Int32Array, counts[Domain.LOOP]))
  mesh.l.next.set(r.read(Int32Array, counts[Domain.LOOP]))
  mesh.f.l.set(r.read(Int32Array, counts[Domain.FACE]))

  const layerCount = r.one()
  for (let i = 0; i < layerCount; i++) {
    const [domain, type, flags, tag] = r.u32(4)
    const [size] = r.u32(2)
    const fill = r.f64()
    const name = r.str()
    const ctor = CTORS[tag] as unknown as {new (n: number): TypedArray; BYTES_PER_ELEMENT: number}
    const data = r.read(ctor, counts[domain] * size)

    const layer = mesh.attrs.add(domain as Domain, name, type as AttrType, flags as AttrFlags, fill)
    if (layer.column.size !== size) {
      throw new Error(`leafmesh: attribute "${name}" declared ${layer.column.size} wide, file has ${size}`)
    }
    layer.column.data.set(data)
  }

  mesh.rebuildDerivedTopo()
  mesh.topoStamp++
  return mesh
}
